enum EAccountState {
  FROZEN = "F",
  NORMAL = "N",
  CANCELED = "C",
}

export enum EHistoryCategory {
  ACCOUNT = "A",
  SYSTEM = "S",
  HISTORY = "H",
}

enum EMilliseconds {
  NOW = 0,
  HOUR = 60 * 60 * 1000,
  DAY = 24 * 60 * 60 * 1000,
  MINUTE = 60 * 1000,
}

enum EStorePrefix {
  SESSION = "SESSION",
  ATTEMPT = "ATTEMPT",
}

enum EJWT {
  EXPIRY_SECONDS = EMilliseconds.HOUR / 1000,
}

enum EMySQLErrorCode {
  ACCESS_DENIED_ERROR = "ACCESS_DENIED_ERROR",
  AUTHENTICATION_PLUGIN_NOT_LOADED = "AUTHENTICATION_PLUGIN_NOT_LOADED",
  BAD_DB_ERROR = "BAD_DB_ERROR",
  CANNOT_ADD_FOREIGN = "CANNOT_ADD_FOREIGN",
  CANNOT_CREATE_TABLE = "CANNOT_CREATE_TABLE",
  CANNOT_DROP_FIELD_OR_KEY = "CANNOT_DROP_FIELD_OR_KEY",
  CANNOT_FIND_UDF = "CANNOT_FIND_UDF",
  CANNOT_LOGIN_WITH_GRANT = "CANNOT_LOGIN_WITH_GRANT",
  CANNOT_RENAME_TABLE = "CANNOT_RENAME_TABLE",
  CANNOT_OPEN_FILE = "CANNOT_OPEN_FILE",
  CANNOT_READ_DIR = "CANNOT_READ_DIR",
  CHECK_NO_SUCH_TABLE = "CHECK_NO_SUCH_TABLE",
  COLUMN_CANT_BE_NULL = "COLUMN_CANT_BE_NULL",
  DATA_TOO_LONG = "DATA_TOO_LONG",
  DUP_ENTRY = "DUP_ENTRY",
  DUPLICATE_COLUMN = "DUPLICATE_COLUMN",
  DUPLICATE_KEY = "DUPLICATE_KEY",
  DUPLICATE_TABLE = "DUPLICATE_TABLE",
  ERROR_DURING_COMMIT = "ERROR_DURING_COMMIT",
  ERROR_DURING_ROLLBACK = "ERROR_DURING_ROLLBACK",
  FOREIGN_DUPLICATE_KEY = "FOREIGN_DUPLICATE_KEY",
  FOREIGN_KEY_EXISTS = "FOREIGN_KEY_EXISTS",
  FOREIGN_KEY_NOT_FOUND = "FOREIGN_KEY_NOT_FOUND",
  FUNCTION_NOT_DEFINED = "FUNCTION_NOT_DEFINED",
  ILLEGAL_REFERENCE = "ILLEGAL_REFERENCE",
  INDEX_COLUMN_TOO_LONG = "INDEX_COLUMN_TOO_LONG",
  INDEX_FILE_FULL = "INDEX_FILE_FULL",
  INNODB_UNDO_RECORD_TOO_BIG = "INNODB_UNDO_RECORD_TOO_BIG",
  KEY_NOT_FOUND = "KEY_NOT_FOUND",
  LOCK_WAIT_TIMEOUT = "LOCK_WAIT_TIMEOUT",
  NO_DEFAULT = "NO_DEFAULT",
  NO_SUCH_TABLE = "NO_SUCH_TABLE",
  NOT_IMPLEMENTED = "NOT_IMPLEMENTED",
  OBJECT_ALREADY_EXISTS = "OBJECT_ALREADY_EXISTS",
  OBJECT_NOT_IN_PREREQUISITE_STATE = "OBJECT_NOT_IN_PREREQUISITE_STATE",
  OUT_OF_MEMORY = "OUT_OF_MEMORY",
  PASSWORD_ANONYMOUS_USER = "PASSWORD_ANONYMOUS_USER",
  PASSWORD_NOT_ALLOWED = "PASSWORD_NOT_ALLOWED",
  QUERY_INTERRUPTED = "QUERY_INTERRUPTED",
  ROW_IS_REFERENCED = "ROW_IS_REFERENCED",
  ROW_IS_REFERENCED_2 = "ROW_IS_REFERENCED_2",
  ROW_SIZE_TOO_LARGE = "ROW_SIZE_TOO_LARGE",
  TOO_MANY_USER_CONNECTIONS = "TOO_MANY_USER_CONNECTIONS",
  UNIQUE_CONSTRAINT_FAILED = "UNIQUE_CONSTRAINT_FAILED",
  UNKNOWN_AUTHID = "UNKNOWN_AUTHID",
  UNKNOWN_CHARACTER_SET = "UNKNOWN_CHARACTER_SET",
  UNKNOWN_COLLATION = "UNKNOWN_COLLATION",
  UNKNOWN_COM_ERROR = "UNKNOWN_COM_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  UNKNOWN_KEY_CACHE = "UNKNOWN_KEY_CACHE",
  UNKNOWN_PARAMETER = "UNKNOWN_PARAMETER",
  UNKNOWN_PARTITION = "UNKNOWN_PARTITION",
  UNKNOWN_STORAGE_ENGINE = "UNKNOWN_STORAGE_ENGINE",
  UNKNOWN_TABLE = "UNKNOWN_TABLE",
  UNKNOWN_USER = "UNKNOWN_USER",
  UNSUPPORTED_EXTENSION = "UNSUPPORTED_EXTENSION",
  VALUE_COUNT_ON_ROW = "VALUE_COUNT_ON_ROW",
  WRONG_COLUMN_NAME = "WRONG_COLUMN_NAME",
  WRONG_VALUE_COUNT = "WRONG_VALUE_COUNT",
}

export default {
  EAccountState,
  EHistoryCategory,
  EMilliseconds,
  EStorePrefix,
  EJWT,
  EMySQLErrorCode,
};
