const {
  DATABASE_HOST,
  DATABASE_USER,
  DATABASE_PASSWORD,
  DATABASE_CONNECTION_LIMIT = 10,
  SESSION_HOST,
  SESSION_PORT = 6379,
  SECRET = "",
  HTTPS,
  SERVICE_PORT = 3000,
  ORIGIN,
} = process.env;

export default {
  DATABASE_HOST,
  DATABASE_USER,
  DATABASE_PASSWORD,
  DATABASE_CONNECTION_LIMIT: Number(DATABASE_CONNECTION_LIMIT),
  SESSION_HOST,
  SESSION_PORT: Number(SESSION_PORT),
  SECRET,
  HTTPS: Boolean(Number(HTTPS)),
  SERVICE_PORT: Number(SERVICE_PORT),
  ORIGIN,
};
