version: "3"

name: account-hub

networks:
  entry:
    name: entry
    labels:
      PROJECT: account-hub

volumes:
  database:
    labels:
      PROJECT: account-hub
  session:
    labels:
      PROJECT: account-hub

services:
  database:
    restart: always
    build:
      labels:
        PROJECT: account-hub
        SERVICE: database
      context: ./database
      dockerfile: Dockerfile
    image: account-hub-database
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=main
      - MYSQL_INITDB_SKIP_TZINFO=${DATABASE_SKIP_TZINFO}
    container_name: database
    networks:
      - entry
    volumes:
      - database:/var/lib/mysql
    ports:
      - ${DATABASE_PORT}:3306

  session:
    restart: always
    build:
      labels:
        PROJECT: account-hub
        SERVICE: session
      context: ./session
      dockerfile: Dockerfile
    image: account-hub-session
    container_name: session
    networks:
      - entry
    volumes:
      - session:/data
    ports:
      - ${SESSION_PORT}:6379

  service:
    restart: always
    build:
      labels:
        PROJECT: account-hub
        SERVICE: service
      context: ./service
      dockerfile: Dockerfile
    image: account-hub-service
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_CONNECTION_LIMIT=${DATABASE_CONNECTION_LIMIT}
      - SESSION_HOST=${SESSION_HOST}
      - SESSION_PORT=${SESSION_PORT}
      - SECRET=${SECRET}
      - HTTPS=${HTTPS}
      - SERVICE_PORT=${SERVICE_PORT}
    container_name: service
    networks:
      - entry
    volumes:
      - ./service/source:/service/source
    ports:
      - 80:${SERVICE_PORT}
    depends_on:
      - database
      - session
