version: "3"

name: account-hub

networks:
  entry:
    name: entry
    labels:
      PROJECT: account-hub

volumes:
  data:
    labels:
      PROJECT: account-hub

services:
  database:
    restart: always
    build:
      labels:
        PROJECT: account-hub
        SERVICE: database
      context: ./database
      dockerfile: Dockerfile
    image: account-hub-database
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=account_hub
      - MYSQL_INITDB_SKIP_TZINFO=${DATABASE_SKIP_TZINFO}
    container_name: database
    networks:
      - entry
    volumes:
      - data:/var/lib/mysql
    ports:
      - ${PORT_DATABASE}:3306

  session:
    restart: always
    build:
      labels:
        PROJECT: account-hub
        SERVICE: session
      context: ./session
      dockerfile: Dockerfile
    image: account-hub-session
    container_name: session
    networks:
      - entry
    ports:
      - ${PORT_SESSION}:6379

  application:
    restart: always
    build:
      labels:
        PROJECT: account-hub
        SERVICE: application
      context: ./application
      dockerfile: Dockerfile
    image: account-hub-application
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=account_hub
      - DATABASE_CONNECTION_LIMIT=${DATABASE_CONNECTION_LIMIT}
      - DATABASE_PORT=${DATABASE_PORT}
      - SESSION_HOST=${SESSION_HOST}
      - SESSION_PORT=${SESSION_PORT}
      - SECRET=${SECRET}
      - HTTPS=${HTTPS}
      - PORT_APPLICATION=${PORT_APPLICATION}
    container_name: application
    networks:
      - entry
    volumes:
      - ./application/source:/application/source
    ports:
      - 80:${PORT_APPLICATION}
    depends_on:
      - database
      - session
