const {
  DATABASE_HOST,
  DATABASE_USER,
  DATABASE_PASSWORD,
  DATABASE_CONNECTION_LIMIT = 10,
  PORT_DATABASE = 3306,
  SESSION_HOST,
  PORT_SESSION = 6379,
  SECRET = "",
  HTTPS,
  PORT_APPLICATION = 3000,
} = process.env;

export default {
  DATABASE_HOST,
  DATABASE_USER,
  DATABASE_PASSWORD,
  DATABASE_CONNECTION_LIMIT: Number(DATABASE_CONNECTION_LIMIT),
  PORT_DATABASE: Number(PORT_DATABASE),
  SESSION_HOST,
  PORT_SESSION: Number(PORT_SESSION),
  SECRET,
  HTTPS: Boolean(HTTPS),
  PORT_APPLICATION: Number(PORT_APPLICATION),
};
