const {
  DATABASE_HOST,
  DATABASE_USER,
  DATABASE_PASSWORD,
  DATABASE_CONNECTION_LIMIT = 10,
  DATABASE_PORT = 3306,
  SESSION_HOST,
  SESSION_PORT = 6379,
  SECRET = "",
  HTTPS,
  APPLICATION_PORT = 3000,
} = process.env;

export default {
  DATABASE_HOST,
  DATABASE_USER,
  DATABASE_PASSWORD,
  DATABASE_CONNECTION_LIMIT: Number(DATABASE_CONNECTION_LIMIT),
  DATABASE_PORT: Number(DATABASE_PORT),
  SESSION_HOST,
  SESSION_PORT: Number(SESSION_PORT),
  SECRET,
  HTTPS: Boolean(HTTPS),
  APPLICATION_PORT: Number(APPLICATION_PORT),
};
